server { 
    # Listen to port 443 on both IPv4 and IPv6. 
    listen 443 ssl; 
    listen 80;
 
    # Domain names this server should respond to. 
    server_name thananont-server-01.centralindia.cloudapp.azure.com; 
 
    # Load the certificate files. 
    ssl_certificate         /etc/letsencrypt/live/thananont-server-01.centralindia.cloudapp.azure.com/fullchain.pem; 
    ssl_certificate_key     /etc/letsencrypt/live/thananont-server-01.centralindia.cloudapp.azure.com/privkey.pem; 
    ssl_trusted_certificate /etc/letsencrypt/live/thananont-server-01.centralindia.cloudapp.azure.com/chain.pem; 
 
    # Load the Diffie-Hellman parameter. 
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem; 
 
    location /profile-images { 
        alias /var/www/html/public/profile-images; 
        try_files $uri =404; 
        add_header Cache-Control "no-store"; 
    } 
 
    location /api { 
        proxy_pass http://backend-server:3000/api; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection 'upgrade'; 
        proxy_http_version 1.1; 
        proxy_cache_bypass $http_upgrade; 
    } 
 
    location / { 
        proxy_pass http://frontend-server:80; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection 'upgrade'; 
        proxy_http_version 1.1; 
        proxy_cache_bypass $http_upgrade; 
    } 
}
